version: '3.8'

networks:
  ym-admin-web:
    driver: bridge

services:
  ym-admin-web:
    container_name: ym-admin-web
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "81:81"
    networks:
      - ym-admin-web
